// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/service/sms/ratelimit/limiter.go
//
// Generated by this command:
//
//	mockgen -source=./internal/service/sms/ratelimit/limiter.go -package=limitersmsmocks -destination=./internal/service/sms/ratelimit/mock/limiter.mock.go
//

// Package limitersmsmocks is a generated GoMock package.
package limitersmsmocks
