// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/cache/code/rediscode.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repository/cache/code/rediscode.go -package=rediscodemocks -destination=./internal/repository/cache/code/mocks/rediscode.mock.go
//

// Package rediscodemocks is a generated GoMock package.
package rediscodemocks
