// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/google/wire"
	"github.com/misakimei123/redbook/interactive/grpc"
	"github.com/misakimei123/redbook/interactive/repository"
	"github.com/misakimei123/redbook/interactive/repository/cache"
	"github.com/misakimei123/redbook/interactive/repository/dao"
	"github.com/misakimei123/redbook/interactive/service"
)

// Injectors from wire.go:

func InitInteractiveService() *grpc.InteractiveServiceServer {
	db := InitDB()
	interactiveDao := dao.NewInteractiveGormDao(db)
	cmdable := InitRedis()
	interactiveCache := cache.NewInteractiveRedisCache(cmdable)
	interactiveRepository := repository.NewCachedInteractiveRepository(interactiveDao, interactiveCache)
	interactiveService := service.NewInteractiveService(interactiveRepository)
	interactiveServiceServer := grpc.NewInteractiveServiceServer(interactiveService)
	return interactiveServiceServer
}

// wire.go:

var (
	thirdPartySet = wire.NewSet(
		InitRedis, InitDB, InitLogger)
	interactiveSvcSet = wire.NewSet(dao.NewInteractiveGormDao, cache.NewInteractiveRedisCache, repository.NewCachedInteractiveRepository, service.NewInteractiveService)
)
